---
####################
# AlertManager stuff
####################

alertmanager_cfg_dir: "/opt/alertmanager"
alertmanager_data_dir: "/data/alertmanager"
alertmanager_data_user: "nobody"
alertmanager_data_group: "nogroup"

alertmanager_version: "latest"
alertmanager_publish_port: "9093"

alertmanager_cpu_limit: "1"
alertmanager_cpu_reserv: "0.25"

alertmanager_mem_limit: "512M"
alertmanager_mem_reserv: "128M"
